/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001848",
        "on-secondary-fixed-variant": "#920024",
        "error-container": "#ffdad6",
        "secondary-container": "#ff5263",
        "primary-fixed": "#dae2ff",
        "outline": "#737685",
        "on-surface": "#191c1e",
        "inverse-primary": "#b2c5ff",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#82f9be",
        "surface": "#f8f9fb",
        "tertiary": "#004e32",
        "secondary-fixed-dim": "#ffb3b4",
        "on-primary-container": "#c4d2ff",
        "outline-variant": "#c3c6d6",
        "tertiary-fixed-dim": "#65dca4",
        "primary": "#003d9b",
        "surface-container-highest": "#e1e2e4",
        "secondary": "#b81a36",
        "on-tertiary-fixed": "#002113",
        "surface-variant": "#e1e2e4",
        "surface-container-low": "#f3f4f6",
        "primary-fixed-dim": "#b2c5ff",
        "inverse-on-surface": "#f0f1f3",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9fb",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d9dadc",
        "surface-tint": "#0c56d0",
        "background": "#f8f9fb",
        "on-tertiary-fixed-variant": "#005235",
        "tertiary-container": "#006844",
        "on-error-container": "#93000a",
        "primary-container": "#0052cc",
        "on-secondary-fixed": "#40000a",
        "error": "#ba1a1a",
        "on-surface-variant": "#434654",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8ea",
        "secondary-fixed": "#ffdad9",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#0040a2",
        "on-background": "#191c1e",
        "inverse-surface": "#2e3132",
        "surface-container": "#edeef0",
        "on-tertiary-container": "#72e9af",
        "on-secondary-container": "#5b0013"
      },
      maxWidth: {
        'xs': '20rem',
        'sm': '24rem',
        'md': '28rem',
        'lg': '32rem',
        'xl': '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
        'full': '100%',
        'screen': '100vw',
        'page': '1200px',
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "lg": "24px",
        "md": "16px",
        "gutter": "24px",
        "xxl": "48px",
        "xl": "32px",
        "base": "8px",
        "xs": "4px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.45", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "600" }],
        "h3": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "h2": ["32px", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h1": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "caption": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.55", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
